version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - nilerr
    - revive
    - unconvert
    - unparam

  settings:
    revive:
      rules:
        - name: var-naming
        - name: unused-parameter
          disabled: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocritic
